#### ______________________________________________________________________________________________________________________
<h1 style="color:#219759;  font-weight: bold;">2.1 : NumPy</h1>
    `

( **Num** erical  **Py** thon)


________________________________________________________________________________________________________________________

<h3 style="color:#49abe3 ; font-weight: bold;">Introduction :</h3>

> NumPy is a powerful library for **numerical computing** in Python.

> It provides **support for arrays, matrices, and many mathematical functions**.

In [2]:
import numpy as np

<h4 style="color:#e86f13 ; font-weight: bold;">NumPy Arrays :</h4>

<h4 style="color:#29bd6f; font-weight: bold;">1)   0-D Array :</h4>

- 0-D array is the simplest form of a NumPy array and is essentially a scalar. 
- It contains a single element.

<h4 style="color:#f84352; font-weight: bold;">Creating Arrays :</h4>

**1. From a Python list:**

In [3]:
arr_0D = np.array([1, 2, 3, 4, 5])
print(arr_0D)

[1 2 3 4 5]


<h4 style="color:#f84352; font-weight: bold;"> Arrays Attributes :</h4>

NumPy arrays have several attributes:

> **shape** : Shape of the arra

> **ndim**  : Number of dimensions

> **size** : Total number of elements

> **dtype** : Data type of elements

***

In [4]:
a = 10
arr_0d = np.array(a)
print(arr_0d)
print(type(arr_0d))

10
<class 'numpy.ndarray'>


In [5]:
arr_0d.shape  # Shape of the array

()

In [6]:
arr_0d.ndim   # Number of dimensions

0

In [7]:
arr_0d.size   # Total number of elements

1

In [8]:
arr_0d.dtype  # Data type of elements

dtype('int64')

<h4 style="color:#29bd6f; font-weight: bold;">2) 1-D Array :</h4>

- **1-D arrays**, also **known as vectors**, are a **fundamental data structure in NumPy**.


<h4 style="color:#f84352; font-weight: bold;">Creating Arrays :</h4>

**1. From a Python list:**

In [9]:
array_1D = np.array([1, 2, 3, 4, 5])
print(array_1D)

[1 2 3 4 5]


**2. Using built-in functions like `np.zeros`, `np.ones`, `np.arange`, and `np.linspace`:**

**i) Zeros:**
- Generate a Arrays of zeros
- **Syntax:** -  : np.zeros(shape)

In [10]:
array_zeros = np.zeros(10)  # Array of zeros

print(array_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**ii) ones:**
- Generate a Arrays of ones
- **Syntax:** -  : np.ones(shape)

In [11]:
array_ones = np.ones(9)    # Array of ones

print(array_ones) 

[1. 1. 1. 1. 1. 1. 1. 1. 1.]


**iii) arange :** 
- arange is an array-valued version of the built-in python range function
- **Syntax -:** np.arrange(start,end,step)  

In [12]:
array_arange = np.arange(10)  # Array with values from 0 to 4

print(array_arange)

[0 1 2 3 4 5 6 7 8 9]


**iv) linespace :** 
- Return evenly spaced Numbers over a specified interval.
- **Syntax -:** np.linespace(start,end,num_of_samples)  

In [13]:
array_linspace = np.linspace(1, 5, 5)  # 5 values between 0 and 1

print(array_linspace)

[1. 2. 3. 4. 5.]


***

In [14]:
# Creating 1D Array
a=[1,2,3]
array_1D = np.array(a)
print(array_1D)

[1 2 3]


In [15]:
array_1D.shape

(3,)

In [16]:
array_1D.ndim

1

In [17]:
array_1D.size

3

In [18]:
array_1D.dtype

dtype('int64')

<h4 style="color:#29bd6f; font-weight: bold;">3) 2-D Array :</h4>

- **2-D arrays**, **also known as matrices**, are a fundamental data structure in NumPy.

<h4 style="color:#f84352; font-weight: bold;">Creating Arrays :</h4>

**1. From a Python list:**

In [19]:
array_2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array_2D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


**2. Using built-in functions like `np.zeros`, `np.ones`, `np.eye`:**

In [20]:
array_zeros = np.zeros((3, 3))  # 3x3 array of zeros

array_ones = np.ones((2, 4))    # 2x4 array of ones

array_identity = np.eye(3)      # 3x3 identity matrix

print(array_zeros, array_ones, array_identity)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] [[1. 1. 1. 1.]
 [1. 1. 1. 1.]] [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


***

In [21]:
# Creating 1D Array
a=[1,2,3]
array_1D = np.array(a)
print(array_1D)

[1 2 3]


In [22]:
array_1D.shape

(3,)

In [23]:
array_1D.ndim

1

In [24]:
array_1D.size

3

In [25]:
array_1D.dtype

dtype('int64')