#### ______________________________________________________________________________________________________________________
<h1 style="color:#219759;  font-weight: bold;">2.1 : NumPy</h1>
    `

( **Num** erical  **Py** thon)


________________________________________________________________________________________________________________________

<h3 style="color:#49abe3 ; font-weight: bold;">Introduction :</h3>

NumPy is a powerful library for **numerical computing** in Python.

- Provides **support for arrays, matrices**, and many **mathematical functions**.
- Designed for **performance**, allowing efficient storage and manipulation of large datasets.
- Supports **n-dimensional arrays** for complex data manipulation and analysis.
- Includes a wide range of **mathematical functions** for operations like linear algebra and statistics.
- Integrates well with other scientific libraries such as **SciPy**, **Pandas**, and **Matplotlib**.
- Introduces **broadcasting**, enabling arithmetic operations on arrays of different shapes.
- Supports **vectorized operations**, eliminating the need for explicit loops.
- Handles various **data types** (integers, floats, complex numbers) for versatile computations.
- Offers advanced **indexing and slicing** capabilities for data extraction and manipulation.
- Backed by a **large community**, providing extensive documentation and resources.

### Procedure:

### 1. Installation

To install NumPy, use pip in your command line or terminal:

```bash
pip install numpy


### 2. Importing NumPy
Before using NumPy, you need to import it in your Python script or Jupyter Notebook as:

import numpy as np


Let's Start : - 

In [158]:
import numpy as np

#### NumPy Arrays:

NumPy arrays are the core data structure of the NumPy library, providing a powerful and efficient way to store and manipulate numerical data. Unlike Python's built-in lists, NumPy arrays are homogeneous, meaning all elements must be of the same data type. This homogeneity allows for more efficient memory use and faster computations.

Key features of NumPy arrays include:

- **N-dimensional support:** NumPy can handle multi-dimensional arrays, making it suitable for complex mathematical operations.
- **Element-wise operations:** You can perform arithmetic operations on arrays element by element, facilitating mathematical computations without the need for explicit loops.
- **Broadcasting:** This feature allows NumPy to perform operations on arrays of different shapes, expanding smaller arrays to match the shape of larger ones during computations.

NumPy arrays are essential for scientific computing and data analysis in Python, providing a foundation for many other libraries, such as SciPy, Pandas, and Matplotlib.

#### Types of Arrays:

1. **0-D Array:** 
   - A scalar value with a single element. 
   - Example: `arr_0D = np.array(42)`

2. **1-D Array:** 
   - A linear array, also known as a vector, containing elements in a single row.
   - Example: `arr_1D = np.array([1, 2, 3, 4, 5])`

3. **2-D Array:** 
   - A matrix consisting of rows and columns.
   - Example: `arr_2D = np.array([[1, 2, 3], [4, 5, 6]])`

4. **3-D Array:** 
   - A multi-dimensional array, often used for representing data with depth (like RGB images).
   - Example: `arr_3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])`

5. **N-D Array:**
   - An array with N dimensions, where N can be any positive integer.
   - Example: `arr_ND = np.random.rand(3, 4, 5)` (a 3-dimensional array with random values)


<h3 style="color:#29bd6f; font-weight: bold;">1) 0-D Array :</h3>

- 0-D array is the simplest form of a NumPy array and is essentially a scalar. 
- It contains a single element.
- Example: `arr_0D = np.array(42)`  # Here, 42 is a constant.
- It can be used to represent fixed values such as numbers or constants in calculations.


<h4 style="color:#f84352; font-weight: bold;">Creating Arrays :</h4>

 **1. From a Python list:**

In [163]:
arr_0D = np.array([1, 2, 3, 4, 5])
print(arr_0D)

[1 2 3 4 5]


***

<h4 style="color:#f84352; font-weight: bold;"> Arrays Attributes :</h4>

NumPy arrays have several attributes:

> **shape** : Shape of the array

> **ndim**  : Number of dimensions

> **size** : Total number of elements

> **dtype** : Data type of elements

In [246]:
a = 10
arr_0d = np.array(a)
print(arr_0d)
print(type(arr_0d))

10
<class 'numpy.ndarray'>


In [248]:
# Shape of the array
arr_0d.shape  

()

In [168]:
# Number of dimensions
arr_0d.ndim   

0

In [236]:
# Total number of elements
arr_0d.size   

1

In [238]:
# Data type of elements
arr_0d.dtype  

dtype('int32')

__________________________________________________________

<h3 style="color:#29bd6f; font-weight: bold;">2) 1-D Array :</h3>

- **1-D arrays**, also **known as vectors**, are a **fundamental data structure in NumPy**.
- They consist of a sequence of elements, all of the same data type.
- Commonly used to represent a list of items or a single dimension of data.
- Can be created from lists, tuples, or using built-in functions like `np.zeros`, `np.ones`, and `np.arange`.


<h4 style="color:#f84352; font-weight: bold;">Creating Arrays :</h4>

**1. From a Python list:**

In [175]:
array_1D = np.array([1, 2, 3, 4, 5])
print(array_1D)

[1 2 3 4 5]


**2. Using built-in functions like `np.zeros`, `np.ones`, `np.arange`, and `np.linspace`:**

**i) Zeros:**
- Generate a Arrays of zeros
- **Syntax:** -  : np.zeros(shape)

In [178]:
array_zeros = np.zeros(10)  # Array of zeros

print(array_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**ii) ones:**
- Generate a Arrays of ones
- **Syntax:** -  : np.ones(shape)

In [180]:
array_ones = np.ones(9)    # Array of ones

print(array_ones) 

[1. 1. 1. 1. 1. 1. 1. 1. 1.]


**iii) arange :** 
- arange is an array-valued version of the built-in python range function
- **Syntax -:** np.arrange(start,end,step)  

In [182]:
array_arange = np.arange(10)  # Array with values from 0 to 4

print(array_arange)

[0 1 2 3 4 5 6 7 8 9]


**iv) linespace :** 
- Return evenly spaced Numbers over a specified interval.
- **Syntax -:** np.linespace(start,  end, num_of_samples)  

In [283]:
array_linspace = np.linspace(1, 5, 5)  # 5 values between 0 and 1

print(array_linspace)

[1. 2. 3. 4. 5.]


***

**Creating 1D Array**

In [269]:
a=[1,2,3]
array_1D = np.array(a)
print(array_1D)

[1 2 3]


In [187]:
# Shape of the array
array_1D.shape

(3,)

In [188]:

array_1D.ndim

1

In [189]:

array_1D.size

3

In [190]:

array_1D.dtype

dtype('int32')

______________________________________________________

<h4 style="color:#29bd6f; font-weight: bold;">3) 2-D Array :</h4>

- **2-D arrays**, **also known as matrices**, are a **fundamental data structure in NumPy**.
- They consist of rows and columns, allowing for more complex data representation.
- Each element is accessed using two indices: one for the row and one for the column.
- Commonly used in mathematical computations, image processing, and data analysis.

<h4 style="color:#f84352; font-weight: bold;">Creating Arrays :</h4>

**1. From a Python list:**

In [255]:
array_2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array_2D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


**2. Using built-in functions like `np.zeros`, `np.ones`, `np.eye`:**

In [272]:
# 3x3 array of zeros

array_zeros = np.zeros((3, 3))  

print(array_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [260]:
# 2x4 array of ones

array_ones = np.ones((2, 4))    

print(array_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [262]:
# 3x3 identity matrix

array_identity = np.eye(3)     

print(array_identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


***

In [265]:
# Creating a 2D array
array_2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


# Printing the attributes of the array

print("Shape:", array_2D.shape)   # (3, 3) - 3 rows and 3 columns

print("Number of dimensions:", array_2D.ndim)    # 2 - Two-dimensional array

print("Size:", array_2D.size)    # 9 - Total number of elements (3*3)

print("Data type:", array_2D.dtype)   # int64 (or similar, depending on the system)


Shape: (3, 3)
Number of dimensions: 2
Size: 9
Data type: int32
